### ISSUE TITLE
NAV BAR

### ISSUE THREAD

**Issue by aruadecarvalho** [chingu-voyages/v42-geckos-team-19#18]
**__Feature Description__**
Describe what the feature is intended to accomplish & why it's important

**__Major User Stories/tasks__**
- [ ] User Story or Task  #1
- [ ] User Story or Task #2
- [ ] Additional User Stories or Tasks as necessary

**__Additional Considerations__**
Include anything else that may be helpful. For example, links to external resources.

**Comment by sittora** [comment]
- [ ] As user I can easily navigate through the website, so I can access the different parts easily
- [ ] As user I can easily login/signup through the auth page, so I can access my account 
- [ ] As user I can read about the company, so I can find out about company’s history
- [ ] As user I  can find our contact information, so I can easily contact the company
- [ ] As user I can browse our products, so I can buy them for myself
- [ ] As user I can check my wishlist section, so I can see the products I’ve saved to buy later 
- [ ] Error messages (page not found and etc)
