### ISSUE TITLE
CHECKOUT PAGE

### ISSUE THREAD

**Issue by aruadecarvalho** [chingu-voyages/v42-geckos-team-19#26]
**__Feature Description__**
Describe what the feature is intended to accomplish & why it's important

**__Major User Stories/tasks__**
- [ ] User Story or Task  #1
- [ ] User Story or Task #2
- [ ] Additional User Stories or Tasks as necessary

**__Additional Considerations__**
Include anything else that may be helpful. For example, links to external resources.

**Comment by Stan-Stani** [comment]
- [ ] change quantity of items from checkout page
